blank_issues_enabled: false
contact_links:
  - name: 🤔 Ask a Question
    url: https://github.com/d2phap/ImageGlass/discussions/new/choose
    about: Ask a question about ImageGlass features.
    
  - name: 🦜 Ask Discord Community
    url: https://discord.gg/tWjbynH2X8
    about: Join in official Discord server of ImageGlass.
