// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:ImageGlass.ImageListView.ImageListViewItemAdaptors.URIAdaptor.GetSourceImage(System.Object)~System.String")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:ImageGlass.ImageListView.ImageListViewItemAdaptors.URIAdaptor.GetThumbnail(System.Object,System.Drawing.Size,ImageGlass.ImageListView.UseEmbeddedThumbnails,System.Boolean,System.Boolean)~System.Drawing.Image")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:ImageGlass.ImageListView.ImageListViewRenderers.NewYear2010Renderer.UpdateTimerCallback(System.Object)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:ImageGlass.ImageListView.MetadataExtractor.ExifDateTime(System.String)~System.DateTime")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:ImageGlass.ImageListView.MetadataExtractor.GetMetadataObject(System.Windows.Media.Imaging.BitmapMetadata,System.String[])~System.Object")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:ImageGlass.ImageListView.MetadataExtractor.InitViaWpf(System.String)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:ImageGlass.ImageListView.QueuedBackgroundWorker.OnRunWorkerCompleted(ImageGlass.ImageListView.QueuedWorkerCompletedEventArgs)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:ImageGlass.ImageListView.QueuedBackgroundWorker.Run")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:ImageGlass.ImageListView.ShellInfoExtractor.FromFile(System.String)~ImageGlass.ImageListView.ShellInfoExtractor")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:ImageGlass.ImageListView.ThumbnailExtractor.FromFile(System.String,System.Drawing.Size,ImageGlass.ImageListView.UseEmbeddedThumbnails,System.Boolean,System.Boolean)~System.Threading.Tasks.Task{System.Drawing.Image}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:ImageGlass.ImageListView.ThumbnailExtractor.FromImage(System.Drawing.Image,System.Drawing.Size,ImageGlass.ImageListView.UseEmbeddedThumbnails,System.Boolean,System.Boolean)~System.Drawing.Image")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:ImageGlass.ImageListView.ThumbnailExtractor.GetRotation(System.Drawing.Image)~System.Int32")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:ImageGlass.ImageListView.ThumbnailExtractor.GetRotation(System.String)~System.Int32")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:ImageGlass.ImageListView.ThumbnailExtractor.GetRotation(System.Windows.Media.Imaging.BitmapFrame)~System.Int32")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:ImageGlass.ImageListView.ThumbnailExtractor.GetThumbnail(System.Windows.Media.Imaging.BitmapFrame,System.Drawing.Size,ImageGlass.ImageListView.UseEmbeddedThumbnails,System.Int32)~System.Drawing.Image")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:ImageGlass.ImageListView.ThumbnailExtractor.GetThumbnailBmp(System.Drawing.Image,System.Drawing.Size,System.Int32)~System.Drawing.Image")]
